apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: control-plane-pdb
  namespace: vm-manager
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: control-plane
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: piko-pdb
  namespace: vm-manager
  labels:
    app.kubernetes.io/name: piko
    app.kubernetes.io/component: proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piko
      app.kubernetes.io/component: proxy
